substitutions:
  name: atom-bluetooth-proxy-xxxxx
  friendly_name: BT Proxy xxxxx
  api_key: 1234abcd=

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: ${api_key}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
