substitutions:
  name: esphome-web-123abc
  friendly_name: Dallas 123abc Green
  api_key: "abcd1234="
  led_red: 0%
  led_green: 100%
  led_blue: 0%
  fan_pin: GPIO26
  dallas_pin: GPIO32
  sensor_name: Thermometer Green
  ap_ssid: Esphome-Web-123abc
  ap_pw: "abc123"

packages:
  dallas_fan: github://wasarob/esphome-atom-lite/themo_with_fan/config.yaml@main
